@startuml
class Firma {
    + Name : string <<get>> <<set>>
    + Firma(wunschname:string)
    + Einstellen(neuerMitarbeiter:Arbeiter) : void
    + Produzieren() : void
}
class "List`1"<T> {
}
Firma o-> "Mitarbeiter<Arbeiter>" "List`1"
@enduml
