@startuml
!include ./Program.puml
!include ./Basics4DoLoop/Program.puml
!include ./RelationAggregation/Rad.puml
!include ./RelationAggregation/Motor.puml
!include ./RelationAggregation/Auto.puml
!include ./RelationAggregation/Program.puml
!include ./Basics7Zahlenraten/Program.puml
!include ./Basics6Array/Program.puml
!include ./Basics2Conditionals/Program.puml
!include ./Basics1HelloWorld/Program.puml
!include ./Basics3ForLoop/Program.puml
!include ./Basics9NullableTypes/Program.puml
!include ./Basics5WhileLoop/Program.puml
!include ./Basics10Parameters/Program.puml
!include ./obj/Debug/net60/Gfu.CSharp.Basics.AssemblyInfo.puml
!include ./obj/Debug/net60/Gfu.CSharp.Basics.GlobalUsings.g.puml
!include ./obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics4DoLoop/obj/Debug/net60/Basics4.DoLoop.GlobalUsings.g.puml
!include ./Basics4DoLoop/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics4DoLoop/obj/Debug/net60/Basics4.DoLoop.AssemblyInfo.puml
!include ./RelationAggregation/obj/Debug/net60/Relation.Aggregation.AssemblyInfo.puml
!include ./RelationAggregation/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./RelationAggregation/obj/Debug/net60/Relation.Aggregation.GlobalUsings.g.puml
!include ./Basics7Zahlenraten/obj/Debug/net60/Basics7.Zahlenraten.GlobalUsings.g.puml
!include ./Basics7Zahlenraten/obj/Debug/net60/Basics7.Zahlenraten.AssemblyInfo.puml
!include ./Basics7Zahlenraten/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics6Array/obj/Debug/net60/Basics6.Array.GlobalUsings.g.puml
!include ./Basics6Array/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics6Array/obj/Debug/net60/Basics6.Array.AssemblyInfo.puml
!include ./Basics2Conditionals/obj/Debug/net60/Basics2.Conditionals.AssemblyInfo.puml
!include ./Basics2Conditionals/obj/Debug/net60/Basics2.Conditionals.GlobalUsings.g.puml
!include ./Basics2Conditionals/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics1HelloWorld/obj/Debug/net60/Basics1.HelloWorld.AssemblyInfo.puml
!include ./Basics1HelloWorld/obj/Debug/net60/Basics1.HelloWorld.GlobalUsings.g.puml
!include ./Basics1HelloWorld/obj/Debug/net60/Basics1.Conditionals.AssemblyInfo.puml
!include ./Basics1HelloWorld/obj/Debug/net60/HalloWelt.AssemblyInfo.puml
!include ./Basics1HelloWorld/obj/Debug/net60/Gfu.CSharp.Basics.AssemblyInfo.puml
!include ./Basics1HelloWorld/obj/Debug/net60/Gfu.CSharp.Basics.GlobalUsings.g.puml
!include ./Basics1HelloWorld/obj/Debug/net60/Basics1.Conditionals.GlobalUsings.g.puml
!include ./Basics1HelloWorld/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics1HelloWorld/obj/Debug/net60/HalloWelt.GlobalUsings.g.puml
!include ./Basics3ForLoop/obj/Debug/net60/Basics3.ForLoop.AssemblyInfo.puml
!include ./Basics3ForLoop/obj/Debug/net60/Basics3.ForLoop.GlobalUsings.g.puml
!include ./Basics3ForLoop/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics9NullableTypes/obj/Debug/net60/Basics9.NullableTypes.GlobalUsings.g.puml
!include ./Basics9NullableTypes/obj/Debug/net60/Basics9.NullableTypes.AssemblyInfo.puml
!include ./Basics9NullableTypes/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics5WhileLoop/obj/Debug/net60/Basics5.WhileLoop.GlobalUsings.g.puml
!include ./Basics5WhileLoop/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include ./Basics5WhileLoop/obj/Debug/net60/Basics5.WhileLoop.AssemblyInfo.puml
!include ./Basics10Parameters/obj/Debug/net60/Basics10.Parameters.GlobalUsings.g.puml
!include ./Basics10Parameters/obj/Debug/net60/Basics10.Parameters.AssemblyInfo.puml
!include ./Basics10Parameters/obj/Debug/net60/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
@enduml
